name: landa
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+11

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  intl: ^0.18.1
  jalalidatepicker: ^1.0.5
  json_annotation: ^4.8.1
  language_code: ^0.4.0
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  pin_code_fields: ^8.0.1
  shamsi_date: ^1.0.2
  shared_preferences: ^2.2.2
  toastification: ^1.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/jsons/
    - assets/img/logo/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan-regular.ttf
          weight: 300
        - asset: assets/fonts/Yekan-light.ttf
          weight: 500
        - asset: assets/fonts/Yekan-bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

