name: landa
description: "A new Flutter project."
publish_to: "none"
version: 1.1.1+12

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  language_code: ^0.5.3+2
  logger: ^2.3.0
  meta_seo: ^3.0.9
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  pin_code_fields: ^8.0.1
  seo_renderer: ^0.6.0
  shamsi_date: ^1.0.2
  shared_preferences: ^2.2.3
  toastification: ^2.0.0
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/jsons/
    - assets/img/logo/
    - .env

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan-regular.ttf
          weight: 300
        - asset: assets/fonts/Yekan-light.ttf
          weight: 500
        - asset: assets/fonts/Yekan-bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
