name: landa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
